### ISSUE TITLE
model fields with baked in units as literals

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/metadata_converter#9]
Fields such as depth are correctly modeled as objects (QuantityValue)

for a field like surf_moisture_ph the unit is baked in

we should do

```yaml
slots:
  surf_moisture_ph:
    range: ph

types:
  ph:
    base:float
  description: >
    a numeric value representing pH
  exact_mappings:
    - UO:nnn
    - UCUM:...
    - qudt:...
```
